#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
# source ./script/bootstrap || exit 1

book_name=$1
snippet_file_name=$2
baked_file=$3
debug_flag=$4

sass_file="./recipes/books/${book_name}/book.scss"

raw_file_name="_temp-bake-snippet.xhtml"

# Check command line args

if [ -z "${book_name}" ]; then
  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  echo 'The required arguments are: book_name, raw_file, baked_file'
  exit 1
fi

if [ ! -f "${snippet_file_name}" ]; then
  echo "ERROR: Could not find the raw HTML file at ${snippet_file_name}"
  exit 1
fi

if [ -z "${baked_file}" ]; then
  echo 'ERROR: You must specify a baked path'
  exit 1
fi

if [ ! -f "${sass_file}" ]; then
  echo "ERROR: Could not find the raw SCSS file at ${sass_file}"
  exit 1
fi


# Convert the snippet (which is HTML + CNXML) into just HTML
xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${snippet_file_name}" > "${raw_file_name}" || exit 1

./script/bake-file "${book_name}" "${raw_file_name}" "${baked_file}" "${debug_flag}"
