#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111


book_name=$1
raw_file=$2
baked_file=$3
debug_flag=$4

sass_file="./recipes/books/${book_name}/book.scss"
css_file="./recipes/output/${book_name}.css"

# Check command line args

[[ "${book_name}" ]] || die 'Argument Missing. You must specify the name of the book as the 1st argument. For example: physics. The required arguments are: book_name, raw_file, baked_file'

[[ -f "${raw_file}" ]] || die "Could not find the raw HTML file at ${raw_file}"

[[ "${baked_file}" ]] || die 'You must specify a baked path'

[[ -f "${sass_file}" ]] || die "Could not find the raw SCSS file at ${sass_file}"


# Remove the baked file if it exists
# [ -e "${baked_file}" ] && rm ${baked_file}
# commented out because it could be /dev/stdout

lcov_file="${baked_file}.lcov"

try cnx-easybake --coverage-file "${lcov_file}" "${debug_flag}" "${css_file}" "${raw_file}" "${baked_file}"

# Validate the cooked file.
# Commented because snippets do not pass the data-type="metadata" validation
# and adding in all those metadata blocks would be cumbersome and distract
# from the actual use-case which is to show snippets.
# cnx-epub-validate-collated ${baked_file}
