#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111


branch_name_with_new_stuff=$(git rev-parse --abbrev-ref HEAD)

# Check that this script is not running in the gh-pages branch
[[ "${branch_name_with_new_stuff}" != "gh-pages" ]] || die "You are running this script in the gh-pages branch. It should be run in another branch (the one with new code changes)"

# Check to make sure there are no uncommitted files
staged_files_count=$(git status -s | wc -l)
if [[ ${staged_files_count} -ne 0 ]]; then
  git status -s
  die "You have uncommitted files. Please commit them first. Aborting."
fi

try git checkout gh-pages
try git pull # In case gh-pages has updated since you last pulled
try git rebase "${branch_name_with_new_stuff}"

try ./script/test
try git add --all styleguide/
try git add --all sassdoc/
try git add --all coverage/
try git commit -m "Updating guide from ${branch_name_with_new_stuff} branch"
try git push --force-with-lease origin gh-pages

try git checkout "${branch_name_with_new_stuff}"
