#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
# source ./script/bootstrap || exit 111

"$(npm bin)/sassdoc" --verbose --dest=./sassdoc/ ./recipes/ || exit 1

>&2 echo "Docs are available at ./sassdoc/ . You can open them in a browser"
