#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# shellcheck disable=SC2046
shellcheck $(find ./script -mindepth 1 -maxdepth 1 -not -path '*/\.*' -not -path '*/README*' -type f) ./books.txt $(find ./concourse -path '*.bash' -type f) >&2
