#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

progress "Checking that HTML snippets and 'magic' XML comments are well-formed XML"

[[ -f "./vendor/rhaptos.cnxmlutils/rhaptos/cnxmlutils/xsl/cnxml-to-html5.xsl" ]] || die "./vendor/rhaptos.cnxmlutils/ does not exist. Try running ./script/setup again"

temp_file="temp-linting.xml"

while IFS= read -r -d '' file_name; do # generic for loop
  # Check that the "Magic" comments are well-formed at this point (early)
  # Send Warning messages to null (stderr)
  xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${file_name}" 2> /dev/null | xmllint --pretty 1 /dev/stdin > /dev/null
  error_status=$?

  if [[ ${error_status} = 0 ]]; then
    xmllint --pretty 1 "${file_name}" > "${temp_file}"
    # Remove the "<?xml version="1.0"?>" at the top of the file
    tail -n +2 > "${file_name}" < "${temp_file}"
    rm "${temp_file}"
  else
    echo "ERROR linting ${file_name}"
    exit 1
  fi

done <   <(find ./recipes/books/*/styleguide/*.snippet.xml ./recipes/mixins/styleguide/*.snippet.xml -print0)
