#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# Verify exportable recipes
do_progress_quiet "Running python tests" \
  try pytest tests

# Make sure the snippets are well-formed XML
do_progress_quiet "Linting and checking XML snippets" \
  ./script/lint-snippets

# do_progress_quiet "Compiling CSS Style files" \
#   ./script/build-styles

# # Test the styles
# do_progress_quiet "Testing CSS Style files" \
#   ./script/test-styles

# Generate the CSS files for books
do_progress_quiet "Compiling CSS Recipe files" \
  ./script/build-recipes

# Run the linter
do_progress_quiet "Running SASS linter" \
  npm run-script lint

do_progress_quiet "Running JS tests" \
  npm run-script test:styles

do_progress_quiet "Looking for unused variables" \
  ./script/find-unused-vars

# Make sure the docs and guides still generate
do_progress_quiet "Building sass docs" \
  ./script/build-docs

# Pull in the BOOK_CONFIGS and BOOK_NAMES
source ./books.txt || exit 1

for recipe_name in "${RECIPE_NAMES[@]}"; do
  # Travis _might_ run out of space in the future. This is here "just in case"
  if [[ ${TRAVIS} = 'true' ]]; then
    if [[ -d "./tmp/" ]]; then
      try rm -rf "./tmp/"
    fi
  fi

  do_progress_quiet "Building styleguide for ${recipe_name}" \
    ./script/build-guide "${recipe_name}"
done



# Generate an index.html page for the styleguide
styleguide_dir="./styleguide/"

echo "<html><body><ul>" > "${styleguide_dir}/index.html"
for recipe_name in "${RECIPE_NAMES[@]}"; do
  echo "<li><a href='./${recipe_name}/'>${recipe_name}</a></li>" >> "${styleguide_dir}/index.html"
done
echo "</ul></body></html>" >> "${styleguide_dir}/index.html"


# Generate an HTML report (if genhtml is installed)
if [[ -n "$(command -v genhtml)" ]]; then
  coverage_files=$(find ./tmp/ -name "*.lcov")
  # shellcheck disable=SC2086
  do_progress_quiet "Building HTML Coverage report at ./coverage/" \
    genhtml --quiet --output ./coverage/ ${coverage_files} ./coverage/*.lcov
fi

# Validate the shell scripts
if [[ $(command -v shellcheck) ]]; then
  do_progress_quiet "Linting shell scripts" \
    ./script/lint-scripts
fi

do_progress_quiet "Linting files" \
  npm run-script lint