#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

do_progress_quiet 'Reinstalling python packages' \
  pip install -U -r requirements.txt

 # Use --force so that the packages are reinstalled
do_progress_quiet "Reinstalling NodeJS package.json" \
  yarn install --prefer-offline --force
