#!/bin/bash

while IFS= read -r -d '' file_name; do # generic for loop
  echo "${file_name}"

  without_ext="$(dirname "${file_name}")/$(basename "${file_name}" .xhtml)"
  snippet_file="${without_ext}.snippet.xml"
  raw_file="${without_ext}.raw.xml"

  if xsltproc ./script/xsl/_xhtml-to-cnxml.xsl "${file_name}" > "${snippet_file}"; then
    xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${snippet_file}" > "${raw_file}"
  else
    exit 1
  fi

  # rm ${snippet_file}
  rm "${raw_file}"
done < <(find ./recipes/books/*/styleguide/*.xhtml -print0)

while IFS= read -r -d '' file_name; do # generic for loop
  echo "${file_name}"

  without_ext="$(dirname "${file_name}")/$(basename "${file_name}" .xhtml)"
  snippet_file="${without_ext}.snippet.xml"
  raw_file="${without_ext}.raw.xml"

  if xsltproc ./script/xsl/_xhtml-to-cnxml.xsl "${file_name}" > "${snippet_file}"; then
    xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${snippet_file}" > "${raw_file}"
  else
    exit 1
  fi

  # rm ${snippet_file}
  rm "${raw_file}"
done < <(find ./recipes/mixins/styleguide/*.xhtml -print0)
